- name: Update hosts with latest packages
  hosts: kubernetes_nodes
  vars:
    ansible_user: admin
  tasks:
    - name: Update cgroups
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(console.*)$'
        line: 'cgroup_enable=memory cgroup_memory=1 \1'
        backrefs: yes
      become: yes
    - name: Reboot the system
      ansible.builtin.reboot:
      become: yes
    - name: Install MicroK8s
      community.general.snap:
        name: microk8s
        classic: yes
      become: yes
    - name: Add alias for kubectl as microk8s kubectl to .bashrc
      ansible.builtin.lineinfile:
        path: /home/admin/.bashrc
        line: 'alias kubectl="microk8s kubectl"'